@startuml
actor people as people
boundary 前端界面 as web
control interact_radar_handlers.py as handler
database mysql as mysql

people -> web:1、点击数据按钮
web ->handler:2、前端带参数请求后端接口
handler -> mysql:3、根据雷达ID查询互动雷达信息
mysql -->handler:4、返回互动雷达查询结果
handler -> mysql:5、根据staff_ext_id查询的员工数据
mysql -->handler:6、返回员工数据查询结果
handler -> mysql:7、根据雷达的自动标签ID查询标签信息
mysql -->handler:8、返回标签信息
handler -> mysql:9、根据雷达的自动标签规则ID查询标签信息
mysql -->handler:10、返回标签信息
handler -> mysql:11、根据雷达ID统计雷达访问情况
mysql -->handler:12、返回统计结果
handler -> mysql:13、根据雷达评分规则ID查询评分规则
mysql -->handler:14、返回评分规则
handler -> mysql:13、根据雷达评分规则的标签列表查询客户标签
mysql -->handler:14、返回客户标签
handler -->web:15、后端组装数据库返回的数据，再返回前端

@enduml