server:
  port: 10888
spring:
  application:
    name: gc-admin
  datasource:
    name: develop
    url: jdbc:mysql://localhost:3306/microwaveDB?useUnicode=true&characterEncoding=utf8&autoReconnect=true
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      password: 123456
      port: 6379
      host: 127.0.0.1
      database: 1

# 注册中心
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    service-url:
#      defaultZone: http://118.31.8.21:8761/eureka/

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  base-packages: com.allen.sys.mapper
